spring:
  application:
    name: vehicles
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        default_schema: vehicles
  flyway:
    schemas: vehicles

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  error:
    include-message: always
  port: 8080